/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticePracticeIdRouteImport } from './routes/practice.$practiceId'

const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticePracticeIdRoute = PracticePracticeIdRouteImport.update({
  id: '/practice/$practiceId',
  path: '/practice/$practiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/protocol': typeof ProtocolRoute
  '/practice/$practiceId': typeof PracticePracticeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/protocol': typeof ProtocolRoute
  '/practice/$practiceId': typeof PracticePracticeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/library': typeof LibraryRoute
  '/profile': typeof ProfileRoute
  '/protocol': typeof ProtocolRoute
  '/practice/$practiceId': typeof PracticePracticeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/library'
    | '/profile'
    | '/protocol'
    | '/practice/$practiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/library'
    | '/profile'
    | '/protocol'
    | '/practice/$practiceId'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/library'
    | '/profile'
    | '/protocol'
    | '/practice/$practiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  LibraryRoute: typeof LibraryRoute
  ProfileRoute: typeof ProfileRoute
  ProtocolRoute: typeof ProtocolRoute
  PracticePracticeIdRoute: typeof PracticePracticeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$practiceId': {
      id: '/practice/$practiceId'
      path: '/practice/$practiceId'
      fullPath: '/practice/$practiceId'
      preLoaderRoute: typeof PracticePracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  LibraryRoute: LibraryRoute,
  ProfileRoute: ProfileRoute,
  ProtocolRoute: ProtocolRoute,
  PracticePracticeIdRoute: PracticePracticeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
